// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmbattmjwriiesibayfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtYmF0dG1qd3JpaWVzaWJheWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODUxMTQsImV4cCI6MjA4NjY2MTExNH0.Wd_e8mzf4EFrXaD4rQCb9Zxv7too5GfOmpsn73yfuh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});